# NumPy

NumPy is a library for the Python programming language, adding support for large, multi-dimensional arrays and matrices, along with a large collection of high-level mathematical functions to operate on these arrays.

In this notebook we'll try various numpy methods and in the process learn more about NumPy.

### Installation

Please follow this [link](https://www.scipy.org/scipylib/download.html)



## Importing NumPy

Once numpy is installed, we can import it in our file

In [2]:
import numpy as np

## NumPy Arrays

In NumPy, strictly 1-D arrays are known as vectors and 2-D arrays are known as matrices (a matrix can also have only one row or one column). With NumPy arrays we can get access to various pre-written functions from NumPy.

### Creating NumPy Arrays

There are various ways to create NumPy Arrays. Some of them are listed below.

1. **From a Python List**

In [3]:
list = ['a', 'b', 'c', 'd']
list

['a', 'b', 'c', 'd']

In [4]:
np.array(list)

array(['a', 'b', 'c', 'd'], dtype='<U1')

In [5]:
list_matrix = [[1, 2, 3, 4, 5, 6, 7, 8, 9]]
list_matrix

[[1, 2, 3, 4, 5, 6, 7, 8, 9]]

In [6]:
np.array(list_matrix)

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

2. **arange method**

    arange ( *starting_number*, *ending_number_plus_one*, *step?* )

    Returns evenly spaced values within a given interval. step is optional

In [7]:
np.arange(1, 11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [8]:
np.arange(5, 60, 5)

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55])

3. **zeros method**

    zeros ( *shape* )
    
    Returns a new array of given shape and type, filled with zeros.

In [9]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [10]:
np.zeros((5, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

4. **ones method**

    ones ( *shape* )

    Returns a new array of given shape and type, filled with ones.

In [11]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [12]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

5. **linspace**

    linspace ( *starting_number*, *ending_number*, *number_of_elements_in_array* )
    
    Returns evenly spaced numbers over a specified interval.

In [13]:
np.linspace(10, 20, 5)

array([10. , 12.5, 15. , 17.5, 20. ])

In [14]:
np.linspace(100, 101, 10)

array([100.        , 100.11111111, 100.22222222, 100.33333333,
       100.44444444, 100.55555556, 100.66666667, 100.77777778,
       100.88888889, 101.        ])

6. **eye**

    eye ( *number_of_rows* )

    Returns a 2-D array with ones on the diagonal and zeros elsewhere. (Returns and identity matrix)

In [15]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### Random

1. **rand**

    rand( *shape* )
    
    Returns random values in a given shape.

In [19]:
np.random.rand(5)

array([0.57518779, 0.19384778, 0.05822256, 0.52577097, 0.32358831])

In [20]:
np.random.rand(3,3)

array([[0.08219678, 0.40733045, 0.06723037],
       [0.33016127, 0.14513998, 0.46526913],
       [0.88019654, 0.76625042, 0.56445156]])

In [21]:
np.random.rand(2,3,4)

array([[[0.36206105, 0.22958154, 0.83319599, 0.4183383 ],
        [0.75208865, 0.57000782, 0.6274128 , 0.04711925],
        [0.09841764, 0.2404794 , 0.11834113, 0.06842973]],

       [[0.55342115, 0.51422024, 0.93572436, 0.37248315],
        [0.97695372, 0.06755545, 0.61327116, 0.07304661],
        [0.36672822, 0.70467334, 0.51199265, 0.55391979]]])

2. **randn**

    randn ( *shape* )
    
    Returns a sample (or samples) from the "standard normal" distribution.

In [22]:
np.random.randn(3)

array([-1.74472597,  2.42935882,  0.75518907])

In [23]:
np.random.randn(4,4)

array([[-0.54118313, -0.05458938,  1.36409615,  1.43589379],
       [-0.71517556,  0.37344659, -0.02012244, -1.10491304],
       [ 0.68427074, -2.12185853, -1.46711563, -0.99789096],
       [-0.44399793,  1.09383996,  0.05156926, -2.12073468]])

3. **randint**
    
    randint( *low*, *high?*, *size?* )
    
    Returns random integers from `low` (inclusive) to `high` (exclusive).

In [31]:
np.random.randint(5)

4

In [32]:
np.random.randint(1,11)

10

In [33]:
np.random.randint(1, 100, 10)

array([10, 36, 22, 90, 95, 32, 99, 76, 35, 49])

In [36]:
np.random.randint(1, 100, (4, 4))

array([[88, 50, 10, 15],
       [24,  8, 97,  6],
       [23, 44,  3, 29],
       [82, 49, 96,  8]])

### Array Attributes

max, min, argmax, argmin

In [16]:
list = np.arange(1,10)

In [17]:
list.max()

9

In [18]:
list.min()

1

In [19]:
list.argmax()

8

In [20]:
list.argmin()

0

### Reshape and Shape

1. **reshape**
    
    reshape ( *shape* )

    Returns an array containing the same data with a new shape.

In [25]:
reshape_list = np.arange(1,10)
reshape_list

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
reshape_list.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

2. **Shape**

    Its an attribute which returns the shape (in a tuple) of the array.

In [4]:
shape_list = np.arange(1,10)
shape_list

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
shape_list.shape

(9,)

In [12]:
shape_list.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
shape_list.reshape(3,3).shape

(3, 3)

### dtype

Its an attribute which returns the data type of the object

In [2]:
list = np.arange(1,11)
list.dtype

dtype('int64')

In [4]:
list = np.array(['a', 'b', 'c'])
list.dtype

dtype('<U1')

### Selection

1. **index-based selection**

    For normal 1-D lists

In [3]:
selection_list = np.arange(1,26)
selection_list

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25])

In [4]:
selection_list[9]

10

In [6]:
selection_list[24]

25

    For 