# NumPy

NumPy is a library for the Python programming language, adding support for large, multi-dimensional arrays and matrices, along with a large collection of high-level mathematical functions to operate on these arrays.

In this notebook we'll try various numpy methods and in the process learn more about NumPy.

### Installation

Please follow this [link](https://www.scipy.org/scipylib/download.html)



## Importing NumPy

Once numpy is installed, we can import it in our file

In [1]:
import numpy as np

## NumPy Arrays

In NumPy, strictly 1-D arrays are known as vectors and 2-D arrays are known as matrices (a matrix can also have only one row or one column). With NumPy arrays we can get access to various pre-written functions from NumPy.

### Creating NumPy Arrays

There are various ways to create NumPy Arrays. Some of them are listed below.

1. **From a Python List**

In [5]:
list = ['a', 'b', 'c', 'd']
list

['a', 'b', 'c', 'd']

In [3]:
np.array(list)

array(['a', 'b', 'c', 'd'], dtype='<U1')

In [8]:
list_matrix = [[1, 2, 3, 4, 5, 6, 7, 8, 9]]
list_matrix

[[1, 2, 3, 4, 5, 6, 7, 8, 9]]

In [9]:
np.array(list_matrix)

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

2. **arange method**

    arange ( *starting_number*, *ending_number_plus_one*, *step?* )

    Returns evenly spaced values within a given interval. step is optional

In [10]:
np.arange(1, 11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [12]:
np.arange(5, 60, 5)

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55])

3. **zeros method**

    zeros ( *shape* )
    
    Returns a new array of given shape and type, filled with zeros.

In [13]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [14]:
np.zeros((5, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

4. **ones method**

    ones ( *shape* )

    Returns a new array of given shape and type, filled with ones.

In [15]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [16]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

5. **linspace**

    linspace ( *starting_number*, *ending_number*, *number_of_elements_in_array* )
    
    Returns evenly spaced numbers over a specified interval.

In [19]:
np.linspace(10, 20, 5)

array([10. , 12.5, 15. , 17.5, 20. ])

In [23]:
np.linspace(100, 101, 10)

array([100.        , 100.11111111, 100.22222222, 100.33333333,
       100.44444444, 100.55555556, 100.66666667, 100.77777778,
       100.88888889, 101.        ])